### ISSUE TITLE
Asyncdisplaykit.org throws invalid certs

### ISSUE THREAD

**Issue by hannahmbanana** [AsyncDisplayKit/Documentation#107]
![screen shot 2017-01-03 at 11 36 34 pm](https://cloud.githubusercontent.com/assets/3419380/24062786/2358cf1a-0b1a-11e7-8ec8-3c06af698316.png)

@garrettmoon - maybe this is something that can get fixed with the website is transferred?

**Comment by garrettmoon** [comment]
This is apparently really difficult to address, GitHub doesn't support https for custom domains.

**Comment by garrettmoon** [comment]
Bottom of the second paragraph: https://help.github.com/articles/securing-your-github-pages-site-with-https/
