### ISSUE TITLE
Add tracking to site

### ISSUE THREAD

**Issue by garrettmoon** [AsyncDisplayKit/Documentation#28]
We should add tracking to the site so we can understand who is visiting and how effective our outreach is.

@hannahmbanana can you look into this?

**Comment by garrettmoon** [comment]
@maicki has suggested Google Analytics and that seems like a pretty good place to start.

**Comment by garrettmoon** [comment]
From Scott:
"I wonder if we can do that on the GitHub landing / readme page in addition to docs
would also like to see if the API Reference pages are ever used - probably less so, maybe not at all"

**Comment by hannahmbanana** [comment]
@garrettmoon @appleguy @maicki - I'll work on this more, but FYI you can already see some interesting statistics under the **Graphs** > **Traffic** tab on GitHub.

![image](https://cloud.githubusercontent.com/assets/3419380/20335332/264802e6-ac05-11e6-929d-9a29070708b5.png)

![image](https://cloud.githubusercontent.com/assets/3419380/20335352/45c69c04-ac05-11e6-9249-b23518e99246.png)

**Comment by hannahmbanana** [comment]
- I followed this guy's [directions](https://desiredpersona.com/google-analytics-jekyll/) to setup the tracking in PR #29.
- I also added the team as admins to the google analytics account.

**Comment by garrettmoon** [comment]
Awesome, thank you @hannahmbanana !

**Comment by hannahmbanana** [comment]
Using Google Analytics, to see the number of visitors for a specific page, go to

**Behavior > Site Content > All Pages**

**Comment by hannahmbanana** [comment]
Between Github Traffic & Google Analytics, I think we have this covered now. Let me know if not.

**Comment by garrettmoon** [comment]
👍 Thanks @hannahmbanana !
