### ISSUE TITLE
Font is too thin

### ISSUE THREAD

**Issue by e-kazakov** [AsyncDisplayKit/Documentation#60]
I find it quite difficult to read [documentation](http://asyncdisplaykit.org/) because font is so thin.

Is there any chance you might consider changing style?

Update: this is valid only for non retina mpb.

**Comment by hannahmbanana** [comment]
@azeff - thanks for reporting this!

@ay8s - did you change the font style when upgrading the website? It looks like the font size maybe smaller. Would you be willing to revert the size?

**Comment by ay8s** [comment]
Sure, will get a tweak in to increase the size/weight shortly. 👍

**Comment by hannahmbanana** [comment]
@ay8s - *poke* :)

**Comment by ay8s** [comment]
@hannahmbanana Remembered earlier today, will get on this when I'm back in SF. Fly out in the morning.

**Comment by e-kazakov** [comment]
Thank you!
